### ISSUE TITLE
[Feature Request] support to add prefix or suffix to origin type keys

### ISSUE THREAD

**Issue by starryforce** [hannq/todash#1]
e.g.

type Origin = {
  test1: string;
  test2: string;
  test3: string;
};

type Posted = {
  test1Post: string;
  test2Post: string;
  test3Post: string;
};

**Comment by hannq** [comment]
```bash
npm i todash@2.3.0 
```

[ObjAddStrKeySuffix](https://hannq.github.io/todash/utils/obj-add-str-key-suffix)

```ts
type Origin = {
  test1: string;
  test2: boolean;
  test3: number;
};

type ObjAfterAddStrKeySuffix = _.ObjAddStrKeySuffix<Origin, 'Aa'>;
// => { test1Aa: string; test2Aa: boolean; test3Aa: number; }
```
